function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "autosar_swc_monitor"};
	this.sidHashMap["autosar_swc_monitor"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "autosar_swc_monitor:3"};
	this.sidHashMap["autosar_swc_monitor:3"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "autosar_swc_monitor:16"};
	this.sidHashMap["autosar_swc_monitor:16"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/TPS_Seconday_Value"] = {sid: "autosar_swc_monitor:4"};
	this.sidHashMap["autosar_swc_monitor:4"] = {rtwname: "<Root>/TPS_Seconday_Value"};
	this.rtwnameHashMap["<Root>/TPS_Primary_Value"] = {sid: "autosar_swc_monitor:6"};
	this.sidHashMap["autosar_swc_monitor:6"] = {rtwname: "<Root>/TPS_Primary_Value"};
	this.rtwnameHashMap["<Root>/Runnable_Step_sys"] = {sid: "autosar_swc_monitor:3"};
	this.sidHashMap["autosar_swc_monitor:3"] = {rtwname: "<Root>/Runnable_Step_sys"};
	this.rtwnameHashMap["<Root>/TPS_Percent_Value"] = {sid: "autosar_swc_monitor:8"};
	this.sidHashMap["autosar_swc_monitor:8"] = {rtwname: "<Root>/TPS_Percent_Value"};
	this.rtwnameHashMap["<S1>/TPS_Seconday_Value_read"] = {sid: "autosar_swc_monitor:5"};
	this.sidHashMap["autosar_swc_monitor:5"] = {rtwname: "<S1>/TPS_Seconday_Value_read"};
	this.rtwnameHashMap["<S1>/TPS_Primary_Value_read"] = {sid: "autosar_swc_monitor:7"};
	this.sidHashMap["autosar_swc_monitor:7"] = {rtwname: "<S1>/TPS_Primary_Value_read"};
	this.rtwnameHashMap["<S1>/Compare To Constant"] = {sid: "autosar_swc_monitor:16"};
	this.sidHashMap["autosar_swc_monitor:16"] = {rtwname: "<S1>/Compare To Constant"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "autosar_swc_monitor:14"};
	this.sidHashMap["autosar_swc_monitor:14"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/Switch"] = {sid: "autosar_swc_monitor:15"};
	this.sidHashMap["autosar_swc_monitor:15"] = {rtwname: "<S1>/Switch"};
	this.rtwnameHashMap["<S1>/TPS_Percent_Value_write"] = {sid: "autosar_swc_monitor:9"};
	this.sidHashMap["autosar_swc_monitor:9"] = {rtwname: "<S1>/TPS_Percent_Value_write"};
	this.rtwnameHashMap["<S2>/u"] = {sid: "autosar_swc_monitor:16:1"};
	this.sidHashMap["autosar_swc_monitor:16:1"] = {rtwname: "<S2>/u"};
	this.rtwnameHashMap["<S2>/Compare"] = {sid: "autosar_swc_monitor:16:2"};
	this.sidHashMap["autosar_swc_monitor:16:2"] = {rtwname: "<S2>/Compare"};
	this.rtwnameHashMap["<S2>/Constant"] = {sid: "autosar_swc_monitor:16:3"};
	this.sidHashMap["autosar_swc_monitor:16:3"] = {rtwname: "<S2>/Constant"};
	this.rtwnameHashMap["<S2>/y"] = {sid: "autosar_swc_monitor:16:4"};
	this.sidHashMap["autosar_swc_monitor:16:4"] = {rtwname: "<S2>/y"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
